name       : mailutils
version    : 2.99.99
release    : 1
source     :
    - http://download.gnu.org.ua/pub/alpha/mailutils/mailutils-2.99.99.tar.xz : fd7743673e81ceb864e0c5876f9304616ca3759d69c662c27d6e093a9919f31d
license    : GPL-3.0
summary    : Mail Utils
description: |
    Mailutils is a swiss army knife of electronic mail handling. It offers a rich set of utilities and daemons for processing the e-mail.
builddeps  :
    - pkgconfig(gnutls)
    - pam-devel
    - pkgconfig(fribidi)
    - pkgconfig(libpq)
setup      : |
    # Patch thanks to Vincent (Serpamplemousse)
    %patch -p1 < $pkgfiles/0001-undefined-references.patch
    %configure --without-ldap --with-gnutls --with-fribidi --with-python --with-postgresql --disable-static
build      : |
    %make -j1
install    : |
    %make_install
