name       : mailutils
version    : 3.16
release    : 16
source     :
    - https://ftp.gnu.org/gnu/mailutils/mailutils-3.16.tar.xz : 041d158d308c0376184388e9c936cfa841a51cdc25d4db75984a771a3fa002c0
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : network.mail
summary    : Mail Utils
description: |
    Mailutils is a swiss army knife of electronic mail handling. It offers a rich set of utilities and daemons for processing the e-mail.
builddeps  :
    - pkgconfig(fribidi)
    - pkgconfig(gnutls)
    - pkgconfig(krb5)
    - pkgconfig(libxcrypt)
    - pkgconfig(python3)
    - gdbm-devel
environment: |
    export CFLAGS="${CFLAGS} -fcommon"
setup      : |
    %patch -p1 < $pkgfiles/fix-mb-len-max.patch

    # Force Python3
    export PYTHON_CONFIG=/usr/bin/python3-config
    export PYTHON=/usr/bin/python3
    %configure --disable-static \
        --enable-ipv6 \
        --without-ldap \
        --with-fribidi \
        --with-gnutls \
        --with-gdbm
build      : |
    %make
install    : |
    %make_install
check      : |
    # CCache and fakeroot both break parts of the tests
    unset LD_PRELOAD
    export CCACHE_DISABLE=1

    %make check
