name       : mailutils
version    : 3.4
release    : 4
source     :
    - ftp://ftp.gnu.org/gnu/mailutils/mailutils-3.4.tar.xz : f39f528cf6eebc9a045658bd98c86619002f06df4664647e4f78e27e90c62173
license    :
    - GPL-3.0
    - LGPL-3.0
component  : network.mail
summary    : Mail Utils
description: |
    Mailutils is a swiss army knife of electronic mail handling. It offers a rich set of utilities and daemons for processing the e-mail.
builddeps  :
    - pkgconfig(fribidi)
    - pkgconfig(gnutls)
    - pkgconfig(libpq)
    - gdbm-devel
    - pam-devel
setup      : |
    %configure --disable-static \
        --enable-ipv6 \
        --without-ldap \
        --with-fribidi \
        --with-gnutls \
        --with-postgres
build      : |
    %make
install    : |
    %make_install
