name       : mailutils
version    : 3.9
release    : 10
source     :
    - https://ftp.gnu.org/gnu/mailutils/mailutils-3.9.tar.xz : 5f736c63b4976c94eaeddadb94d9c257760e6cb2a9fa189cd59600aaa8703dbc
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : network.mail
summary    : Mail Utils
description: |
    Mailutils is a swiss army knife of electronic mail handling. It offers a rich set of utilities and daemons for processing the e-mail.
builddeps  :
    - pkgconfig(fribidi)
    - pkgconfig(gnutls)
    - pkgconfig(krb5)
    - pkgconfig(libpq)
    - pkgconfig(python3)
    - gdbm-devel
environment: |
    export CFLAGS="${CFLAGS} -fcommon"
setup      : |
    %patch -p1 < $pkgfiles/fix-mb-len-max.patch
    patch -t -E < $pkgfiles/python3.patch
    export PYTHON_CONFIG=/usr/bin/python3-config
    export PYTHON=/usr/bin/python3
    %configure --disable-static \
        --enable-ipv6 \
        --without-ldap \
        --with-fribidi \
        --with-gnutls \
        --with-postgres
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check || :

